spring:
  datasource:
    url: ${CP_OF_ICRITIC_DB_URL:jdbc:postgresql://localhost:5432/copyOfIcritic}
    username: ${CP_OF_ICRITIC_DB_USERNAME:postgres}
    password: ${CP_OF_ICRITIC_DB_PASSWORD:postgres}
  jpa:
    database: POSTGRESQL
  error:
    include-stacktrace: never
server:
  error:
    include-stacktrace: never